### ISSUE TITLE
Server event SocketRequested -> AddSocket

### ISSUE THREAD

**Issue by jensulrich** [joneisen/AloeExpress#7]
If I use version 2019 Release 2.1 it seems, I have to change the SocketRequested event (back) to the AddSocket event to avoid a NilObject Exception

**Comment by joneisen** [comment]
I have to look into this. I haven't updated AloeExpress to Xojo 2019R2.1 yet and I'll try to get to it in the next day or two.

**Comment by joneisen** [comment]
Sorry for the delay. This appears to be a bug in Xojo and I've reported it in Xojo Feedback [Case #58725](feedback://showreport?report_id=58725)
